# Generated by Django 6.0.6 on 2026-06-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='rfid_tag',
            field=models.CharField(blank=True, help_text='Unique RFID tag identifier attached to the vehicle chassis.', max_length=50, null=True, unique=True),
        ),
    ]
