# Generated by Django 6.0.6 on 2026-07-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_marineoperator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarineOperator',
        ),
        migrations.CreateModel(
            name='ArchivedVehicle',
            fields=[
            ],
            options={
                'verbose_name': 'Archived / Disposed Asset',
                'verbose_name_plural': 'Archived / Disposed Assets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fleet.vehicle',),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('OPERATIONAL', 'Operational'), ('MAINTENANCE', 'Maintenance'), ('DEPLOYED', 'Deployed')], default='OPERATIONAL', max_length=50),
        ),
    ]
