# Generated by Django 6.0.6 on 2026-06-29 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_issue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardNotification',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='part',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='vehicleissue',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='vehicleissue',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='vehicletype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vehicletype',
            name='icon_class',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='assigned_driver',
            field=models.CharField(blank=True, default='None Assigned', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('FUNCTIONING', '⚙️ Functioning'), ('UNDER MAINTENANCE', '🔧 Under Maintenance'), ('OUT OF ORDER', '🚨 Out of Order')], default='FUNCTIONING', max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='fleet.vehicletype'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
        migrations.DeleteModel(
            name='MaintenanceRecord',
        ),
        migrations.DeleteModel(
            name='VehicleIssue',
        ),
    ]
