# Generated by Django 6.0.6 on 2026-06-29 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_delete_dashboardnotification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='assigned_driver',
            field=models.CharField(default='None Assigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('OPERATIONAL', 'Operational'), ('MAINTENANCE', 'Maintenance'), ('DEPLOYED', 'Deployed')], default='OPERATIONAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.vehicletype'),
        ),
    ]
