# Generated by Django 6.0.6 on 2026-06-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_alter_vehicle_assigned_driver_alter_vehicle_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='driver_phone',
            field=models.CharField(blank=True, default='', help_text='e.g., +639123456789', max_length=20),
        ),
    ]
